oauth2:
  google:
    key: "501372861749-o1sh3tjn8gatkb12gt86lgp73giaaen2.apps.googleusercontent.com"
    secret: "LuPpKooujbH-Vbpkc5ykfTPY"
session:
  secret: mikamaifuscmikamaifuscmikamaifuscmikamaifuscmikamaifuscmikamai
